services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ddroot
      MYSQL_DATABASE: flowly-db
      MYSQL_USER: dduser
      MYSQL_PASSWORD: ddpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
